apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx-1
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - name: config-volume-1
        mountPath: /usr/share/nginx/html
  volumes:
    - name: config-volume-1
      configMap:
        name: nginx-configmap-1
        items: 
          - key: index1.html
            path: index.html
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx-2
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - name: config-volume-2
        mountPath: /usr/share/nginx/html
  volumes:
    - name: config-volume-2
      configMap:
        name: nginx-configmap-2
        items: 
          - key: index2.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-1
data:
  index1.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Esercitazione</title>
    </head>
    <body>
      <h1>MY CONTAINER - pod-1</h1>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-2
data:
  index2.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Esercitazione</title>
    </head>
    <body>
      <h1>MY CONTAINER - pod-2</h1>
    </body>
    </html>